# -*- coding: utf-8 -*-
"""SuperCaptionModel2.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQvgu6eyi_9WE-ehFPKnyL6i58wyGGua
"""

import os

from google.colab import drive
drive.mount('/content/drive')


PROJECT_DIR = "/content/drive/MyDrive/officehome_caption_project"

DATA_DIR = os.path.join(PROJECT_DIR, "data")
FAISS_DIR = os.path.join(PROJECT_DIR, "faiss_index")
MODEL_DIR = os.path.join(PROJECT_DIR, "models")
OUTPUT_DIR = os.path.join(PROJECT_DIR, "outputs")
LOG_DIR = os.path.join(OUTPUT_DIR, "logs")

for path in [PROJECT_DIR, DATA_DIR, FAISS_DIR, MODEL_DIR, OUTPUT_DIR, LOG_DIR]:
  os.makedirs(path, exist_ok=True)
print("프로젝트 폴더 생성 완료")
print(PROJECT_DIR)

cnn_checkpoint_path = "/content/drive/MyDrive/models/officehome_convnext_phase_center_best.pt"

print("checkpoint 존재:", os.path.exists(cnn_checkpoint_path))
print("checkpoint 경로:", cnn_checkpoint_path)

#Drive 폴더로 캡션 복사


from google.colab import files
uploaded = files.upload()

import shutil
src = "/content/office_home_image_caption_cleaned_metadata.csv"
dst_dir = "/content/drive/MyDrive/officehome_caption_project/data"
dst = f"{dst_dir}/office_home_image_caption_cleaned_metadata.csv"

shutil.copy(src, dst)

csv_path = "/content/drive/MyDrive/officehome_caption_project/data/office_home_enriched_metadata.csv"

!pip install -q sentence-transformers faiss-cpu
import pandas as pd

df = pd.read_csv(csv_path)

df.head()

#검색용 문장 만들기

def make_search_text(row):
  object_name = str(row.get("object", "")).replace("_", " ")
  domain = str(row.get("domain", ""))
  size = str(row.get("size", ""))
  price = str(row.get("price_usd", ""))
  caption = str(row.get("caption", ""))


  text = (
      f"object : {object_name} . "
      f"Domain : {domain}."
      f"Size : {size}"
      f"Price : {price} USD."
      f"Caption : {caption}. "
  )

  return text


df["search_text"] = df.apply(make_search_text, axis =1)
df[["object", "caption", "search_text"]].head()

#


from sentence_transformers import SentenceTransformer
import numpy as np

embedding_model_name = "sentence-transformers/all-MiniLM-L6-v2"

model = SentenceTransformer(embedding_model_name)

texts = df["search_text"].fillna("").tolist()

embeddings= model.encode(
    texts,
    batch_size = 64,
    show_progress_bar = True,
    convert_to_tensor = True,
    normalize_embeddings=True
)

print("임베딩 shape", embeddings.shape)

!pip install -q faiss-cpu

import faiss
import numpy as np
import torch

if isinstance(embeddings, torch.Tensor):
  embeddings_np = embeddings.detach().cpu().numpy()
else :
  embeddings_np = embeddings

embeddings_np = embeddings_np.astype("float32")

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)
index.add(embeddings)

import json

faiss_index_path = os.path.join(FAISS_DIR , "officehome_caption.index")
metadata_path = os.path.join(DATA_DIR, "officehome_search_metadata.csv")
config_path = os.path.join(FAISS_DIR, "officehome_caption_config.json")

faiss.write_index(index, faiss_index_path)

df.to_csv(metadata_path, index=False)

config = {
    "embedding_model_name": embedding_model_name,
    "embedding_dim ": int(dimension),
    "num_vectors" : int(index.ntotal),
    "metadata_path" : metadata_path,
    "faiss_index_path" : faiss_index_path
}

with open(config_path, "w", encoding="utf-8") as f:
  json.dump(config, f, ensure_ascii=False, indent=2)

def search_caption(query, top_k =5):
  query_vec = model.encode(
      [query],
      convert_to_numpy=True,
      normalize_embeddings=True
  ).astype("float32")


  scores, indices = index.search(query_vec, top_k)


  results = df.iloc[indices[0]].copy()
  results["score"] = scores[0]

  cols = ["score", "object", "size", "price_usd", "caption", "image_url", "source_filepath"]
  available_cols = [c for c in cols if c in results. columns]

  return results[available_cols]


search_caption("black moniter with a stand", top_k =5)

import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

print("전체 데이터 수:", len(df))
print("컬럼 목록:", df.columns.tolist())

print("\ncaption 결측치 개수:", df["caption"].isna().sum())
print("caption 빈 문자열 개수:", (df["caption"].fillna("").str.strip() == "").sum())

df[["object", "size", "price_usd", "caption"]].head(10)

## 여기서부터 gradio 작업 시작



!pip install -q gradio


PROJECT_DIR = "/content/drive/MyDrive/officehome_caption_project"
DATA_DIR = os.path.join(PROJECT_DIR, "data")
FAISS_DIR =os.path.join(PROJECT_DIR, 'faiss_index')

faiss_index_path = os.path.join(FAISS_DIR, "officehome_caption.index")
metadata_path = os.path.join(DATA_DIR, "officehome_search_metadata.csv")
config_path = os.path.join(FAISS_DIR, "officehome_caption_config.json")

#config 불러오기
with open(config_path, "r", encoding="utf-8") as f:
  config = json.load(f)

embedding_model_name = config["embedding_model_name"]


#모델, metadata, FAISS index 불러오기

model = SentenceTransformer(embedding_model_name)
df = pd.read_csv(metadata_path)
index = faiss.read_index(faiss_index_path)


#혹시 이름 바꾸면 이거 쓰기
# faiss_index_path = os.path.join(FAISS_DIR, "네가_저장한_index_파일명.index")
# metadata_path = os.path.join(DATA_DIR, "네가_저장한_metadata_파일명.csv")
# config_path = os.path.join(FAISS_DIR, "네가_저장한_config_파일명.json")

print(config)
print(config.keys())

def search_caption_gradio(query, top_k) :
  if query is None or query.strip() == "":
    return pd.DataFrame({"message" : ["검색어를 입력해주세요."]})

  top_k = int(top_k)

  query_vec = model.encode(
      [query],
      convert_to_numpy=True,
      normalize_embeddings=True
  ).astype("float32")

  scores, indices = index.search(query_vec, top_k)

  results = df.iloc[indices[0]].copy()
  results["score"] = scores[0]

  cols =[
      "score",
      "object",
      "domain",
      "size",
      "price_usd",
      "caption",
      "image_url",
      "source_filepath"
  ]


  available_cols = [c for c in cols if c in results.columns]

  results = results[available_cols]


  #score 반올림 보기 좋으라고
  if "score" in results.columns :
    results["score"] = results["score"].round(4)

    return results

search_caption_gradio("black moniter with a stand ", 5)

import gradio as gr

with gr.Blocks(title="OfficeHome Caption Search") as demo :
  gr.Markdown(
      """
      자연어 검색어를 입력하면,
      SentenceTransformer + FAISS를 이용해 가장 유사한 이미지 캡션 데이털르 검색합니다
      """
  )


  with gr.Row():
    query_input = gr.Textbox(
        label="검색어",
        placeholder="예 : black moniter with a stand / 투명한 물병 / small alarm"
    )

    top_k_input = gr.Slider(
        minimum=1,
        maximum=20,
        value=5,
        step=1,
        label="검색 결과 개수"
    )

  search_button = gr.Button("검색하기")

  result_table = gr.Dataframe(
     label = "검색결과",
     wrap=True
 )

  search_button.click(
      fn =search_caption_gradio,
      inputs=[query_input, top_k_input],
      outputs=result_table
)


demo.launch(share=True)

import gradio as gr

with gr.Blocks(title="OfficeHome Caption Search") as demo:
    gr.Markdown(
        """
        # OfficeHome Caption Search

        자연어 검색어를 입력하면,
        FAISS가 가장 유사한 이미지 캡션 데이터를 찾아 이미지 카드로 보여줍니다.
        """
    )

    with gr.Row():
        query_input = gr.Textbox(
            label="검색어",
            placeholder="예: black monitor with a stand / 투명한 물병 / small alarm clock",
            lines=2
        )

        top_k_input = gr.Slider(
            minimum=1,
            maximum=12,
            value=5,
            step=1,
            label="검색 결과 개수"
        )

    search_button = gr.Button("검색하기")

    result_html = gr.HTML(label="검색 결과")

    search_button.click(
        fn=search_caption_gradio,
        inputs=[query_input, top_k_input],
        outputs=result_html
    )

demo.launch(share=True)

test_queries = [
    "real world alarm clock",
    "catalog photo of an alarm clock",
    "black monitor with a stand",
    "product photo of a monitor",
    "bottle for water",
    "office chair product image",
    "yellow pencil for writing",
    "computer keyboard on a desk"
]

for q in test_queries:
    print("\n" + "=" * 100)
    print("QUERY:", q)
    display(search_caption_gradio(q, 5))

import os
import json

PROJECT_DIR = "/content/drive/MyDrive/officehome_caption_project"
DATA_DIR = os.path.join(PROJECT_DIR, "data")
FAISS_DIR = os.path.join(PROJECT_DIR, "faiss_index")

metadata_path = os.path.join(DATA_DIR, "officehome_search_metadata.csv")
faiss_index_path = os.path.join(FAISS_DIR, "officehome_caption.index")
config_path = os.path.join(FAISS_DIR, "officehome_caption_config.json")

config = {
    "embedding_model_name": "sentence-transformers/all-MiniLM-L6-v2",
    "metadata_path": metadata_path,
    "faiss_index_path": faiss_index_path,
    "index_type": "IndexFlatIP",
    "normalize_embeddings": True,
    "description": "OfficeHome caption metadata FAISS search index"
}

with open(config_path, "w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print("caption config 저장 완료")
print(config)

import os
import json
import faiss
import pandas as pd
from sentence_transformers import SentenceTransformer

CAPTION_SEARCH_LOADED = False

def load_caption_search_once():
    global CAPTION_SEARCH_LOADED
    global caption_model, caption_df, caption_index

    if CAPTION_SEARCH_LOADED:
        print("Caption search는 이미 로드되어 있습니다.")
        return caption_model, caption_df, caption_index

    PROJECT_DIR = "/content/drive/MyDrive/officehome_caption_project"
    FAISS_DIR = os.path.join(PROJECT_DIR, "faiss_index")

    config_path = os.path.join(FAISS_DIR, "officehome_caption_config.json")

    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    embedding_model_name = config["embedding_model_name"]
    metadata_path = config["metadata_path"]
    faiss_index_path = config["faiss_index_path"]

    caption_model = SentenceTransformer(embedding_model_name)
    caption_df = pd.read_csv(metadata_path)
    caption_index = faiss.read_index(faiss_index_path)

    CAPTION_SEARCH_LOADED = True

    print("Caption search 로드 완료")
    print("Embedding model:", embedding_model_name)
    print("Metadata shape:", caption_df.shape)
    print("FAISS vector count:", caption_index.ntotal)

    return caption_model, caption_df, caption_index

def search_caption_gradio(query, top_k=5):
    if query is None or query.strip() == "":
        return pd.DataFrame({"message": ["검색어를 입력해주세요."]})

    top_k = int(top_k)

    query_vec = caption_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    scores, indices = caption_index.search(query_vec, top_k)

    results = caption_df.iloc[indices[0]].copy()
    results["score"] = scores[0]

    cols = [
        "score",
        "object",
        "domain",
        "size",
        "price_usd",
        "caption",
        "image_url",
        "source_filepath"
    ]

    available_cols = [c for c in cols if c in results.columns]
    results = results[available_cols]

    if "score" in results.columns:
        results["score"] = results["score"].round(4)

    return results

import io
import base64
import torch
import torch.nn.functional as F
from PIL import Image

# ---------------------------------------------------
# 1. CNN으로 업로드 이미지 분류
#    (cnn_model, cnn_val_transform, classes, device 가 이미 로드되어 있다고 가정)
# ---------------------------------------------------
def predict_image_class(pil_image):
    if pil_image is None:
        return None, None

    image = pil_image.convert("RGB")
    image_tensor = cnn_val_transform(image).unsqueeze(0).to(device)

    cnn_model.eval()
    with torch.no_grad():
        logits = cnn_model(image_tensor)
        probs = F.softmax(logits, dim=1)
        conf, pred_idx = torch.max(probs, dim=1)

    pred_class = classes[pred_idx.item()]
    confidence = float(conf.item())

    return pred_class, confidence


# ---------------------------------------------------
# 2. PIL 이미지를 HTML에 표시할 수 있게 base64 변환
# ---------------------------------------------------
def pil_to_base64(pil_image, max_size=(220, 220)):
    img = pil_image.copy()
    img.thumbnail(max_size)

    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode("utf-8")
    return f"data:image/png;base64,{encoded}"


# ---------------------------------------------------
# 3. 검색 결과를 HTML 카드 형태로 변환
# ---------------------------------------------------
def dataframe_to_result_html(results_df, title="검색 결과", extra_info=""):
    if results_df is None or len(results_df) == 0:
        return f"""
        <div style="padding:16px; border:1px solid #ddd; border-radius:12px;">
            <h3>{title}</h3>
            <p>검색 결과가 없습니다.</p>
            <div>{extra_info}</div>
        </div>
        """

    html = f"""
    <div style="padding:16px;">
        <h3>{title}</h3>
        <div style="margin-bottom:12px;">{extra_info}</div>
    """

    for _, row in results_df.iterrows():
        image_url = row["image_url"] if "image_url" in row else ""
        score = row["score"] if "score" in row else ""
        obj = row["object"] if "object" in row else ""
        domain = row["domain"] if "domain" in row else ""
        size = row["size"] if "size" in row else ""
        price_usd = row["price_usd"] if "price_usd" in row else ""
        caption = row["caption"] if "caption" in row else ""
        source_filepath = row["source_filepath"] if "source_filepath" in row else ""

        html += f"""
        <div style="
            border:1px solid #ddd;
            border-radius:14px;
            padding:14px;
            margin-bottom:14px;
            display:flex;
            gap:16px;
            align-items:flex-start;
            background:#fafafa;
        ">
            <div style="min-width:180px;">
                <img src="{image_url}" style="width:180px; border-radius:10px; border:1px solid #eee;" />
            </div>
            <div style="flex:1;">
                <p><b>score</b>: {score:.4f}</p>
                <p><b>object</b>: {obj}</p>
                <p><b>domain</b>: {domain}</p>
                <p><b>size</b>: {size}</p>
                <p><b>price_usd</b>: {price_usd}</p>
                <p><b>caption</b>: {caption}</p>
                <p><b>source</b>: {source_filepath}</p>
            </div>
        </div>
        """

    html += "</div>"
    return html


# ---------------------------------------------------
# 4. 기존 텍스트 검색용 Gradio 함수
#    (search_caption(query, top_k)는 이미 만들어져 있다고 가정)
# ---------------------------------------------------
def search_caption_text_gradio(query, top_k):
    if query is None or str(query).strip() == "":
        return """
        <div style="padding:16px; border:1px solid #ddd; border-radius:12px;">
            검색어를 입력해주세요.
        </div>
        """

    top_k = int(top_k)
    results = search_caption(query, top_k=top_k)

    extra_info = f"""
    <div style="padding:10px; background:#f3f4f6; border-radius:10px;">
        <b>입력 검색어:</b> {query}
    </div>
    """

    return dataframe_to_result_html(results, title="텍스트 검색 결과", extra_info=extra_info)


# ---------------------------------------------------
# 5. 이미지 + 텍스트 결합 검색용 함수
# ---------------------------------------------------
def search_image_and_caption_gradio(image, query, top_k):
    if image is None and (query is None or str(query).strip() == ""):
        return """
        <div style="padding:16px; border:1px solid #ddd; border-radius:12px;">
            이미지 또는 검색어 중 하나 이상 입력해주세요.
        </div>
        """

    pred_class, confidence = None, None
    image_html = ""

    # 1) 이미지가 있으면 CNN 분류
    if image is not None:
        pred_class, confidence = predict_image_class(image)
        img_b64 = pil_to_base64(image)

        image_html = f"""
        <div style="display:flex; gap:16px; align-items:flex-start; margin-bottom:16px;">
            <img src="{img_b64}" style="width:180px; border-radius:12px; border:1px solid #ddd;" />
            <div style="padding:10px; background:#eef6ff; border-radius:10px;">
                <p><b>CNN 예측 클래스:</b> {pred_class}</p>
                <p><b>예측 확률:</b> {confidence:.4f}</p>
            </div>
        </div>
        """

    # 2) 최종 검색어 만들기
    query = "" if query is None else str(query).strip()

    if pred_class is not None and query != "":
        final_query = f"{query}, {pred_class}"
    elif pred_class is not None:
        final_query = pred_class
    else:
        final_query = query

    # 3) FAISS 검색
    top_k = int(top_k)
    results = search_caption(final_query, top_k=top_k)

    extra_info = f"""
    {image_html}
    <div style="padding:10px; background:#f3f4f6; border-radius:10px;">
        <p><b>사용자 입력 문장:</b> {query if query != '' else '(없음)'}</p>
        <p><b>최종 검색어:</b> {final_query}</p>
    </div>
    """

    return dataframe_to_result_html(results, title="이미지 + 텍스트 검색 결과", extra_info=extra_info)

import gradio as gr

with gr.Blocks(title="OfficeHome Search System") as demo:
    gr.Markdown(
        """
        # OfficeHome Search System

        아래 두 가지 방식으로 검색할 수 있습니다.

        1. **텍스트 검색**
           - 자연어 검색어로 캡션/메타데이터 검색

        2. **이미지 + 텍스트 검색**
           - 이미지를 업로드하면 CNN이 먼저 분류하고,
           - 그 결과를 이용해 FAISS 캡션 검색을 수행
        """
    )

    with gr.Tabs():

        # ---------------------------------------------------
        # 탭 1: 텍스트 검색
        # ---------------------------------------------------
        with gr.Tab("텍스트 검색"):
            with gr.Row():
                text_query_input = gr.Textbox(
                    label="검색어",
                    placeholder="예: black monitor with a stand / transparent water bottle / small alarm clock",
                    lines=2
                )

                text_top_k_input = gr.Slider(
                    minimum=1,
                    maximum=12,
                    value=5,
                    step=1,
                    label="검색 결과 개수"
                )

            text_search_button = gr.Button("텍스트 검색하기")
            text_result_html = gr.HTML(label="텍스트 검색 결과")

            text_search_button.click(
                fn=search_caption_text_gradio,
                inputs=[text_query_input, text_top_k_input],
                outputs=text_result_html
            )

        # ---------------------------------------------------
        # 탭 2: 이미지 + 텍스트 검색
        # ---------------------------------------------------
        with gr.Tab("이미지 + 텍스트 검색"):
            with gr.Row():
                image_input = gr.Image(
                    type="pil",
                    label="이미지 업로드"
                )

                with gr.Column():
                    image_query_input = gr.Textbox(
                        label="추가 설명(선택)",
                        placeholder="예: black monitor with a stand / office product / screen only",
                        lines=2
                    )

                    image_top_k_input = gr.Slider(
                        minimum=1,
                        maximum=12,
                        value=5,
                        step=1,
                        label="검색 결과 개수"
                    )

                    image_search_button = gr.Button("이미지 + 텍스트 검색하기")

            image_result_html = gr.HTML(label="이미지 + 텍스트 검색 결과")

            image_search_button.click(
                fn=search_image_and_caption_gradio,
                inputs=[image_input, image_query_input, image_top_k_input],
                outputs=image_result_html
            )

demo.launch(share=True)

PROJECT_DIR = "."

cnn_checkpoint_path = "/content/drive/MyDrive/models/officehome_convnext_phase_center_best.pt"

PROJECT_DIR = "officehome_caption_project"

metadata_path = f"{PROJECT_DIR}/officehome_search_metadata.csv"
index_path = f"{PROJECT_DIR}/officehome_caption.index"
config_path = f"{PROJECT_DIR}/officehome_caption_config.json"

cnn_checkpoint_path = "models/officehome_convnext_phase_center_best.pt"


import torch
import torch.nn as nn
from torchvision import models, transforms

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

cnn_checkpoint_path = "/content/drive/MyDrive/models/officehome_convnext_phase_center_best.pt"

checkpoint = torch.load(cnn_checkpoint_path, map_location=device)

classes = checkpoint["classes"]
num_classes = len(classes)

cnn_model = models.convnext_tiny(weights=None)

in_features = cnn_model.classifier[2].in_features
cnn_model.classifier[2] = nn.Sequential(
    nn.Dropout(p=0.2),
    nn.Linear(in_features, num_classes))

cnn_model.load_state_dict(checkpoint["model_state_dict"])
cnn_model = cnn_model.to(device)
cnn_model.eval()

cnn_val_transform = transforms.Compose([
    transforms.Resize((224, 384)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print("CNN 모델 로드 완료")
print("클래스 수:", len(classes))
print("클래스 예시:", classes[:10])

import gradio as gr

with gr.Blocks(title="OfficeHome CNN + Caption Search") as demo:
    gr.Markdown("""
    # OfficeHome CNN + Caption Search

    이미지를 업로드하면 CNN이 클래스를 예측하고,
    그 예측 결과를 Caption Search에 연결합니다.
    """)

    with gr.Tab("이미지 + 텍스트 검색"):
        image_input = gr.Image(
            type="pil",
            label="이미지 업로드"
        )

        image_query_input = gr.Textbox(
            label="추가 검색어",
            placeholder="예: black monitor, office desk item, transparent bottle",
            lines=2
        )

        image_top_k_input = gr.Slider(
            minimum=1,
            maximum=12,
            value=5,
            step=1,
            label="검색 결과 개수"
        )

        image_search_button = gr.Button("이미지 기반 검색하기")

        image_result_html = gr.HTML(
            label="이미지 + 텍스트 검색 결과"
        )

        image_search_button.click(
            fn=search_image_and_caption_gradio,
            inputs=[image_input, image_query_input, image_top_k_input],
            outputs=image_result_html
        )

    with gr.Tab("텍스트 검색"):
        text_query_input = gr.Textbox(
            label="검색어",
            placeholder="예: monitor, laptop, desk lamp, transparent bottle",
            lines=2
        )

        text_top_k_input = gr.Slider(
            minimum=1,
            maximum=12,
            value=5,
            step=1,
            label="검색 결과 개수"
        )

        text_search_button = gr.Button("텍스트 검색하기")

        text_result_html = gr.HTML(
            label="텍스트 검색 결과"
        )

        text_search_button.click(
            fn=search_caption_text_gradio,
            inputs=[text_query_input, text_top_k_input],
            outputs=text_result_html
        )

demo.launch()

import os
import shutil
import json

# =========================
# 1. Colab / Drive 원본 경로
# =========================

DRIVE_CAPTION_PROJECT_DIR = "/content/drive/MyDrive/officehome_caption_project"

# 네가 실제로 찾은 CNN 모델 경로로 수정
DRIVE_CNN_MODEL_PATH = "/content/drive/MyDrive/models/officehome_convnext_phase_center_best.pt"

# =========================
# 2. Hugging Face 제출용 폴더
# =========================

HF_SPACE_DIR = "/content/officehome_hf_space"

HF_MODEL_DIR = os.path.join(HF_SPACE_DIR, "models")
HF_CAPTION_PROJECT_DIR = os.path.join(HF_SPACE_DIR, "officehome_caption_project")
HF_FAISS_DIR = os.path.join(HF_CAPTION_PROJECT_DIR, "faiss_index")

os.makedirs(HF_MODEL_DIR, exist_ok=True)
os.makedirs(HF_CAPTION_PROJECT_DIR, exist_ok=True)
os.makedirs(HF_FAISS_DIR, exist_ok=True)

# =========================
# 3. CNN 모델 복사
# =========================

shutil.copy2(
    DRIVE_CNN_MODEL_PATH,
    os.path.join(HF_MODEL_DIR, "officehome_convnext_phase_center_best.pt")
)

print("CNN 모델 복사 완료")

# =========================
# 4. Caption 프로젝트 파일 복사
# =========================

# faiss_index 폴더 전체 복사
drive_faiss_dir = os.path.join(DRIVE_CAPTION_PROJECT_DIR, "faiss_index")

for filename in os.listdir(drive_faiss_dir):
    src = os.path.join(drive_faiss_dir, filename)
    dst = os.path.join(HF_FAISS_DIR, filename)

    if os.path.isfile(src):
        shutil.copy2(src, dst)

print("FAISS 폴더 복사 완료")

# metadata csv가 project 루트에 있는 경우 복사
for filename in os.listdir(DRIVE_CAPTION_PROJECT_DIR):
    src = os.path.join(DRIVE_CAPTION_PROJECT_DIR, filename)
    dst = os.path.join(HF_CAPTION_PROJECT_DIR, filename)

    if os.path.isfile(src) and filename.endswith(".csv"):
        shutil.copy2(src, dst)
        print("metadata 복사:", filename)

print("Hugging Face 제출용 폴더 생성 완료:", HF_SPACE_DIR)

import os
import json

HF_SPACE_DIR = "/content/officehome_hf_space"

config_path = os.path.join(
    HF_SPACE_DIR,
    "officehome_caption_project",
    "faiss_index",
    "officehome_caption_config.json"
)

with open(config_path, "r", encoding="utf-8") as f:
    config = json.load(f)

print("수정 전 config:")
print(json.dumps(config, ensure_ascii=False, indent=2))

# =========================
# Hugging Face Space 기준 상대경로로 수정
# =========================

config["metadata_path"] = "officehome_caption_project/officehome_search_metadata.csv"
config["faiss_index_path"] = "officehome_caption_project/faiss_index/officehome_caption.index"

with open(config_path, "w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print("\n수정 후 config:")
print(json.dumps(config, ensure_ascii=False, indent=2))

requirements_text = """gradio
torch
torchvision
pandas
numpy
Pillow
sentence-transformers
faiss-cpu
"""

requirements_path = "/content/officehome_hf_space/requirements.txt"

with open(requirements_path, "w", encoding="utf-8") as f:
    f.write(requirements_text)

print("requirements.txt 생성 완료:", requirements_path)

import os
import json
import faiss
import pandas as pd
from sentence_transformers import SentenceTransformer

import io
import base64
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models, transforms
from PIL import Image
import gradio as gr


# =========================
# Hugging Face Space 상대경로
# =========================

PROJECT_DIR = "officehome_caption_project"
FAISS_DIR = os.path.join(PROJECT_DIR, "faiss_index")

config_path = os.path.join(FAISS_DIR, "officehome_caption_config.json")

cnn_checkpoint_path = "models/officehome_convnext_phase_center_best.pt"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/officehome_hf_space

CAPTION_SEARCH_LOADED = False

def load_caption_search_once():
    global CAPTION_SEARCH_LOADED
    global caption_model, caption_df, caption_index

    if CAPTION_SEARCH_LOADED:
        print("Caption search는 이미 로드되어 있습니다.")
        return caption_model, caption_df, caption_index

    PROJECT_DIR = "officehome_caption_project"
    FAISS_DIR = os.path.join(PROJECT_DIR, "faiss_index")

    config_path = os.path.join(FAISS_DIR, "officehome_caption_config.json")

    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    embedding_model_name = config["embedding_model_name"]
    metadata_path = "/content/drive/MyDrive/officehome_caption_project/data/officehome_search_metadata.csv"
    faiss_index_path = config["faiss_index_path"]

    caption_model = SentenceTransformer(embedding_model_name)
    caption_df = pd.read_csv(metadata_path)
    caption_index = faiss.read_index(faiss_index_path)

    CAPTION_SEARCH_LOADED = True

    print("Caption search 로드 완료")
    print("Embedding model:", embedding_model_name)
    print("Metadata shape:", caption_df.shape)
    print("FAISS vector count:", caption_index.ntotal)

    return caption_model, caption_df, caption_index


caption_model, caption_df, caption_index = load_caption_search_once()


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

cnn_checkpoint_path = "models/officehome_convnext_phase_center_best.pt"

checkpoint = torch.load(cnn_checkpoint_path, map_location=device)

classes = checkpoint["classes"]
num_classes = len(classes)

cnn_model = models.convnext_tiny(weights=None)

in_features = cnn_model.classifier[2].in_features

cnn_model.classifier[2] = nn.Sequential(
    nn.Dropout(p=0.2),
    nn.Linear(in_features, num_classes)
)

cnn_model.load_state_dict(checkpoint["model_state_dict"])
cnn_model = cnn_model.to(device)
cnn_model.eval()

cnn_val_transform = transforms.Compose([
    transforms.Resize((224, 384)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print("CNN 모델 로드 완료")
print("클래스 수:", len(classes))

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file.lower().endswith(".csv"):
            if "metadata" in file.lower() or "caption" in file.lower() or "officehome" in file.lower():
                print(os.path.join(root, file))

!pip install -U huggingface_hub

from huggingface_hub import login

login()


from huggingface_hub import HfApi

api = HfApi()

api.upload_folder(
    folder_path="/content/officehome_hf_space",
    repo_id = "spsychic2/officehome-cnn-caption-search",
    repo_type = "space"
)