# -*- coding: utf-8 -*-
"""SuperProject_Edit_Only.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vo20rMQu3MWxmi4miptW8G6dFnveUwJP
"""

!pip install -q datasets

from datasets import load_dataset
from huggingface_hub import login
login()
# Login using e.g. `huggingface-cli login` to access this dataset



# FiftyOne 방식
!pip install fiftyone

import fiftyone as fo
import fiftyone.utils.huggingface as fouh

dataset = fouh.load_from_hub("Voxel51/Office-Home")
session = fo.launch_app(dataset)

#위에 까지는 설치. 여기서부터 실제 데이터 다루는 코드. 여기서부터 실행 시키기 1

import os

save_dir = "/content/drive/MyDrive/officehome_resnet18"
os.makedirs(save_dir, exist_ok=True)

print("저장 폴더:", save_dir)



from google.colab import drive
drive.mount('/content/drive')

base_dir = "/content/drive/MyDrive/datasets"

!rm -rf /content/office_home
import os

!rm -rf /content/office_home

!rsync -ah --progress \
"/content/drive/MyDrive/datasets/office_home_fiftyone_export/" \
"/content/office_home/"

#실행 x

!tar -cf "/content/drive/MyDrive/datasets/office_home_local_ready.tar" -C /content office_home

!tar -tf "/content/drive/MyDrive/datasets/office_home_local_ready.tar" | head -30

#이거부터 실행시키면 된대 근데 이거 잘 봐야됨 또 되는지 안되는지 확인을 해봐야 함

from google.colab import drive
drive.mount("/content/drive")

import os

tar_path = "/content/drive/MyDrive/datasets/office_home_local_ready.tar"

!rm -rf /content/office_home

!tar -xf "{tar_path}" -C /content #tar_path 파일을 content에 풀어라

data_dir = "/content/office_home"

print("data_dir 존재:", os.path.exists(data_dir))
print("폴더 예시:", os.listdir(data_dir)[:20])

from torchvision import datasets

temp_dataset = datasets.ImageFolder(root=data_dir)

print("이미지 수:", len(temp_dataset))
print("클래스 수:", len(temp_dataset.classes))
print("클래스 예시:", temp_dataset.classes[:10])

new_tar_path = "/content/drive/MyDrive/datasets/office_home_fiftyone_export_ready.tar"

# 기존 같은 이름의 tar가 있으면 삭제
if os.path.exists(new_tar_path):
    print("기존 새 tar 삭제:", new_tar_path)
    !rm -f "{new_tar_path}"

# Drive 원본 폴더를 tar로 묶기
!tar -cf "{new_tar_path}" -C "/content/drive/MyDrive/datasets" "office_home_fiftyone_export"

print("새 tar 생성 완료:", new_tar_path)

# 크기 확인
print("tar 파일 존재:", os.path.exists(new_tar_path))
print("tar 파일 크기 GB:", round(os.path.getsize(new_tar_path) / (1024**3), 3))

import os
from google.colab import drive
drive.mount("/content/drive")

import os

drive_data_dir = "/content/drive/MyDrive/datasets/office_home_fiftyone_export"

print("Drive 원본 폴더 존재:", os.path.exists(drive_data_dir))

if os.path.exists(drive_data_dir):
    print("Drive 원본 폴더 목록 예시:")
    print(os.listdir(drive_data_dir)[:30])
image_exts = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

def scan_image_folder(root_dir):
    class_counts = {}

    for class_name in sorted(os.listdir(root_dir)):
        class_dir = os.path.join(root_dir, class_name)

        if not os.path.isdir(class_dir):
            continue

        image_count = 0

        for filename in os.listdir(class_dir):
            if filename.lower().endswith(image_exts):
                image_count += 1

        if image_count > 0:
            class_counts[class_name] = image_count

    return class_counts


drive_counts = scan_image_folder(drive_data_dir)

print("Drive 클래스 수:", len(drive_counts))
print("Drive 이미지 수:", sum(drive_counts.values()))

print("\n클래스별 이미지 수 예시:")
for class_name, count in list(drive_counts.items())[:20]:
    print(class_name, count)

data_dir = "/content/office_home"

archive_path = "/content/drive/MyDrive/datasets/office_home_local_ready.tar"

print("tar 존재:", os.path.exists(archive_path))

# 기존 로컬 폴더 정리
!rm -rf /content/office_home
!rm -rf /content/office_home_fiftyone_export

# tar 풀기
!tar -xf "{archive_path}" -C /content

print("압축 해제 후 /content 목록:")
print(os.listdir("/content")[:50])

!tar -tf "/content/drive/MyDrive/datasets/office_home_fiftyone_export_ready.tar" | head -50

# 기존 로컬 폴더 정리
!rm -rf /content/office_home_fiftyone_export
!rm -rf /content/office_home

# 새 tar 풀기
!tar -xf "/content/drive/MyDrive/datasets/office_home_fiftyone_export_ready.tar" -C /content

import os

restored_dir = "/content/office_home_fiftyone_export"

print("복원 폴더 존재:", os.path.exists(restored_dir))

if os.path.exists(restored_dir):
    print("복원 폴더 예시:")
    print(os.listdir(restored_dir)[:20])

data_dir = "/content/office_home_fiftyone_export"

restored_counts = scan_image_folder(data_dir)

print("복원 클래스 수:", len(restored_counts))
print("복원 이미지 수:", sum(restored_counts.values()))

print("\n복원 클래스 예시:")
for class_name, count in list(restored_counts.items())[:20]:
    print(class_name, count)

from google.colab import drive
drive.mount('/content/drive')



#다음으로 넘어갈 곳

import random
import time
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim

from PIL import Image
from tqdm.auto import tqdm

from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

seed= 42

random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed) #cpU 쪽 랜덤성을 고정하는 코드
torch.cuda.manual_seed_all(seed) # GPU 쪽 랜덤성을 고정하는 코드

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device" ,device)

if torch.cuda.is_available():
  print("GPU", torch.cuda.get_device_name(0))

image_exts = (".jpg", ".jpeg", ".png", ".bmp", ".webp") #이런 파일만 인정시킴

temp_dataset = datasets.ImageFolder(root=data_dir)
class_to_idx = temp_dataset.class_to_idx

rows = []
bad_files = []

for class_name, label in tqdm(class_to_idx.items(), desc="metadata 생성"): #items 가 이 내부 데이터를 쌍으로 꺼내줌 키 밸류 이런식으로
    class_dir = os.path.join(data_dir, class_name)

    if not os.path.isdir(class_dir):
        continue #실제 폴더인지 확인함

    for filename in os.listdir(class_dir):
        if filename.lower().endswith(image_exts):
            image_path = os.path.join(class_dir, filename)

            try:
                with Image.open(image_path) as img:
                    img.verify() #검사한다

                rows.append({
                    "image_path": image_path,
                    "filename": filename,
                    "class_name": class_name,
                    "label": label
                })

            except Exception as e:
                bad_files.append({
                    "image_path": image_path,
                    "filename": filename,
                    "class_name": class_name,
                    "label": label,
                    "error": str(e)
                })

metadata_df = pd.DataFrame(rows)
bad_df = pd.DataFrame(bad_files)

print("정상 이미지 수:", len(metadata_df))
print("문제 이미지 수:", len(bad_df))
print("클래스 수:", metadata_df["class_name"].nunique())
print(metadata_df.head())

metadata_csv_path = "/content/drive/MyDrive/datasets/officehome_metadata_cnn_clean.csv"
bad_csv_path = "/content/drive/MyDrive/datasets/officehome_bad_images.csv"

metadata_df.to_csv(metadata_csv_path, index=False)
bad_df.to_csv(bad_csv_path, index=False)

print("metadata 저장:", metadata_csv_path)
print("bad images 저장:", bad_csv_path)

train_df, val_df = train_test_split(
    metadata_df,
    test_size=0.3,
    random_state=seed,
    stratify=metadata_df["label"] #클래스 비율이 비슷하게 들어가돌고 나눠라
)

train_csv_path = "/content/drive/MyDrive/datasets/officehome_train_cnn_clean.csv"
val_csv_path = "/content/drive/MyDrive/datasets/officehome_val_cnn_clean.csv"

train_df.to_csv(train_csv_path, index=False)
val_df.to_csv(val_csv_path, index=False)

print("train 수:", len(train_df))
print("val 수:", len(val_df))
print("train 클래스 수:", train_df["class_name"].nunique())
print("val 클래스 수:", val_df["class_name"].nunique())

class OfficeHomeDualViewDataset(Dataset):
    def __init__(self, csv_path, transform_global=None, transform_local=None):
        self.df = pd.read_csv(csv_path)
        self.transform_global = transform_global
        self.transform_local = transform_local

    def __len__(self): #Dataloader가 전체 데이터 개수를 알아야 batch 를 만들 수 있어서 꼭 필요함
        return len(self.df)

    def __getitem__(self, idx): # idx 번째 데이터를 꺼내는 함수
        row = self.df.iloc[idx]

        image_path = row["image_path"]
        label = int(row["label"])

        image = Image.open(image_path).convert("RGB")


        if self.transform_global :
          image_global = self.transform_global(image)
        else :
          image_global = image

        if self.transform_local :
          image_local = self.transform_local(image)
        else :
          image_local = image



        return image_global, image_local, label

class OfficeHomeCSVDataset(Dataset):
    def __init__(self, csv_path, transform=None, return_path=False):
        self.df = pd.read_csv(csv_path)
        self.transform = transform
        self.return_path = return_path

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        image_path = row["image_path"]
        label = int(row["label"])

        image = Image.open(image_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        if self.return_path:
            return image, label, image_path

        return image, label

#6.15추가사항
consistency_local_transform = transforms.Compose([
    transforms.Resize((224, 384)),

    transforms.RandomHorizontalFlip(p=0.5),

    transforms.RandomApply([
        transforms.RandomResizedCrop(
            size=(224, 384),
            scale=(0.88, 1.0),
            ratio=(0.9, 1.1)
        )
    ], p=0.3),

    transforms.RandomApply([
        transforms.GaussianBlur(
            kernel_size=3,
            sigma=(0.1, 0.7)
        )
    ], p=0.2),

    transforms.ColorJitter(
        brightness=0.10,
        contrast=0.10,
        saturation=0.10,
        hue=0.03
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

train_transform = transforms.Compose([
    transforms.Resize((224, 384)),

    transforms.RandomHorizontalFlip(p=0.6), #좌우 반전 시킴  60% 확률로 반전시킴
    transforms.RandomResizedCrop( #이미지를 랜덤하게 잘라낸 뒤 다시 지정한 크기로 맞춘다
        size=(224, 384),
        scale=(0.85,1.0), #원본 이미지 면적의 85% ~ 100% 사이를 랜덤하게 자름
        ratio =(0.9, 1.1)), #잘라낼 영역의 가로세로 비율 범위


    transforms.RandomApply([ #이 안에 들어있는 변환을 25% 확률로 진행한다
        transforms.GaussianBlur( #이게 적용된 것 이미지를 살짝 흐리게 만드는 역할 값을 조정하는 역할인듯
            kernel_size=3,
            sigma=(0.1, 0.8) #강도를 안에서 랜덤하게 적용
        )
     ], p=0.25),

    transforms.ColorJitter( #색깔, 밝기, 대비 변화
        brightness = 0.2,
        contrast=0.2, #대비변화
        saturation=0.2, # 채도 변화
        hue=0.05 #색상 변화
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
    ])

val_transform = transforms.Compose([
    transforms.Resize((224, 384)),

    transforms.ToTensor(),

    transforms.Normalize( #정규화된 값 = (원래 값 - 평균) / 표준 편차
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

train_dataset = OfficeHomeDualViewDataset(
    csv_path=train_csv_path,
    transform_global=train_transform,
    transform_local = consistency_local_transform
)
val_dataset = OfficeHomeCSVDataset(
    csv_path=val_csv_path,
    transform=val_transform
)
clean_train_dataset = OfficeHomeCSVDataset(
    csv_path=train_csv_path,
    transform=val_transform
)


batch_size = 16

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=0,
    pin_memory=True if torch.cuda.is_available() else False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=0,
    pin_memory=True if torch.cuda.is_available() else False
)

clean_train_loader = DataLoader(
    clean_train_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=0,
    pin_memory=True if torch.cuda.is_available() else False
)

print("train_dataset:", len(train_dataset))
print("val_dataset:", len(val_dataset))
print("clean_train_dataset:", len(clean_train_dataset))

#6.11추가사항
phase15_train_transform = transforms.Compose([
    transforms.Resize((224, 384)),

    # 좌우 위치/방향 의존 줄이기
    transforms.RandomHorizontalFlip(p=0.6),

    # 일부 샘플만 약하게 crop
    # 전체 구조를 크게 망가뜨리지 않도록 scale을 0.92 이상으로 유지
    transforms.RandomApply([
        transforms.RandomResizedCrop(
            size=(224, 384),
            scale=(0.92, 1.0),
            ratio=(0.9, 1.1)
        )
    ], p=0.25),

    # 선명한 국소 특징만 보는 습관 완화
    transforms.RandomApply([
        transforms.GaussianBlur(
            kernel_size=3,
            sigma=(0.1, 0.8)
        )
    ], p=0.15),

    # 색/밝기 shortcut 완화
    transforms.ColorJitter(
        brightness=0.12,
        contrast=0.12,
        saturation=0.12,
        hue=0.03
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

#6.15 추가사항
import torch.nn.functional as F

def consistency_kl_loss(logits_global, logits_local, temperature=1.0):
    p_global = F.softmax(logits_global / temperature, dim=1).detach()
    log_p_local = F.log_softmax(logits_local / temperature, dim=1) #여기서 temperature 는 softmax 분포를 부드럽게 만들거나 날카롭게 만든느 값
    #dim=1은 class 방향으로 계산 0이면 batch 방향

 #logit : 모델이 softmax를 거치기 전에 뱉는 원점수 그니까 날것 그대로의 점수 여기에 softmax를 적용하면 이제 확률이 됨
    loss = F.kl_div(
        log_p_local,
        p_global,
        reduction="batchmean"
    ) * (temperature ** 2)

    return loss



def train_one_epoch_mixup_global_consistency(
    model,
    train_loader,
    criterion,
    optimizer,
    device,
    alpha=0.2,
    consistency_weight=0.2,
    temperature=1.0
):
    model.train()

    running_loss = 0.0
    running_mixup_loss = 0.0
    running_consistency_loss = 0.0

    correct_ref = 0
    total = 0

    start_time = time.time()

    progress_bar = tqdm(
        train_loader,
        desc=f"Training MixUp + GlobalLocal Consistency alpha={alpha}",
        leave=True
    )

    for batch_idx, (images_global, images_local, labels) in enumerate(progress_bar):
        batch_start = time.time()

        images_global = images_global.to(device, non_blocking=True)
        images_local = images_local.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        # MixUp은 global view 기준으로 적용
        mixed_images, labels_a, labels_b, lam = mixup_data(
            images_global,
            labels,
            alpha=alpha
        )

        optimizer.zero_grad(set_to_none=True)

        with autocast():
            # 1. MixUp classification loss
            outputs_mix = model(mixed_images)

            loss_mix = mixup_criterion(
                criterion,
                outputs_mix,
                labels_a,
                labels_b,
                lam
            )
# 2. Global-Local consistency

            # 같은 이미지의 두 view를 비교함

            with torch.no_grad():
              outputs_global = model(images_global)
            outputs_local = model(images_local)

            loss_consistency = consistency_kl_loss(
                logits_global=outputs_global,
                logits_local=outputs_local,
                temperature=temperature
            )

            loss = loss_mix + consistency_weight * loss_consistency

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item() * labels.size(0)
        running_mixup_loss += loss_mix.item() * labels.size(0)
        running_consistency_loss += loss_consistency.item() * labels.size(0)

        # MixUp acc는 참고값
        _, preds = torch.max(outputs_mix, 1)
        correct_ref += (preds == labels_a).sum().item()
        total += labels.size(0)

        current_loss = running_loss / total
        current_mixup_loss = running_mixup_loss / total
        current_consistency_loss = running_consistency_loss / total
        current_acc_ref = correct_ref / total
        batch_time = time.time() - batch_start

        progress_bar.set_postfix({
            "loss": f"{current_loss:.4f}",
            "mix": f"{current_mixup_loss:.4f}",
            "cons": f"{current_consistency_loss:.4f}",
            "acc_ref": f"{current_acc_ref:.4f}",
            "sec/batch": f"{batch_time:.2f}"
        })

    epoch_time = time.time() - start_time

    epoch_loss = running_loss / total
    epoch_acc_ref = correct_ref / total
    epoch_mixup_loss = running_mixup_loss / total
    epoch_consistency_loss = running_consistency_loss / total

    return (
        epoch_loss,
        epoch_acc_ref,
        epoch_mixup_loss,
        epoch_consistency_loss,
        epoch_time
    )

#6.14 추가사항
def mixup_data(images, labels, alpha=0.2):
    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1.0

    batch_size = images.size(0)
    index = torch.randperm(batch_size).to(images.device)

    mixed_images = lam * images + (1 - lam) * images[index]

    labels_a = labels
    labels_b = labels[index]

    return mixed_images, labels_a, labels_b, lam


def mixup_criterion(criterion, outputs, labels_a, labels_b, lam):
    loss_a = criterion(outputs, labels_a)
    loss_b = criterion(outputs, labels_b)

    return lam * loss_a + (1 - lam) * loss_b

#6.14 추가사항
def evaluate_clean_train_acc(
    model,
    train_loader,
    criterion,
    device,
    max_batches=None
):
    model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    start_time = time.time()

    with torch.no_grad():
        for batch_idx, (images, labels) in enumerate(tqdm(train_loader, desc="Clean Train Eval", leave=True)):
            if max_batches is not None and batch_idx >= max_batches:
                break

            images = images.to(device)
            labels = labels.to(device)

            with autocast():
                outputs = model(images)
                loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)

            _, preds = torch.max(outputs, 1)

            correct += (preds == labels).sum().item()
            total += labels.size(0)

    epoch_time = time.time() - start_time

    clean_loss = running_loss / total
    clean_acc = correct / total

    return clean_loss, clean_acc, epoch_time



def add_dropout_to_convnext_classifier(model, dropout_p=0.1):
    old_head = model.classifier[2]

    if isinstance(old_head, nn.Sequential):
        print("classifier가 이미 Sequential입니다. Dropout 추가 생략")
        return model

    if not isinstance(old_head, nn.Linear):
        raise TypeError(f"예상한 Linear가 아닙니다: {type(old_head)}")

    in_features = old_head.in_features
    out_features = old_head.out_features

    new_head = nn.Sequential(
        nn.Dropout(p=dropout_p),
        nn.Linear(in_features, out_features)
    )

    with torch.no_grad():
        new_head[1].weight.copy_(old_head.weight)
        new_head[1].bias.copy_(old_head.bias)

    model.classifier[2] = new_head

    print(f"Dropout 추가 완료: p={dropout_p}")

    return model

#6.14
def freeze_convnext_front_keep_last(model):
    for param in model.parameters():
        param.requires_grad = False

    for param in model.features[-1].parameters():
        param.requires_grad = True

    for param in model.classifier.parameters():
        param.requires_grad = True

    trainable_count = sum(
        p.numel() for p in model.parameters()
        if p.requires_grad
    )
    total_count = sum(p.numel() for p in model.parameters())

    print("Phase 2 freeze 완료")
    print("학습 가능 파라미터 수:", trainable_count)
    print("전체 파라미터 수:", total_count)
    print("학습 가능 비율:", round(trainable_count / total_count, 4))

    return model

#6.18추가사항
class CenterLoss(nn.Module):
    def __init__(self, num_classes, feat_dim, device):
        super().__init__()

        self.num_classes = num_classes
        self.feat_dim = feat_dim

        self.centers = nn.Parameter(
            torch.randn(num_classes, feat_dim).to(device)
        )

    def forward(self, features, labels):
        """
        features: [batch, feat_dim]
        labels  : [batch]
        """
        batch_centers = self.centers[labels]

        loss = ((features - batch_centers) ** 2).sum(dim=1).mean() / 2.0

        return loss


def convnext_forward_with_features(model, images):
    """
    ConvNeXt에서 classifier 직전 feature와 logits를 함께 반환.
    Dropout을 classifier에 추가한 경우도 대응.
    """

    x = model.features(images)
    x = model.avgpool(x)

    # classifier[0] = LayerNorm2d
    # classifier[1] = Flatten
    # classifier[2] = Linear 또는 Sequential(Dropout, Linear)
    x = model.classifier[0](x)
    features = model.classifier[1](x)

    logits = model.classifier[2](features)

    return logits, features


def get_convnext_feature_dim(model):
    head = model.classifier[2]

    if isinstance(head, nn.Linear):
        return head.in_features

    if isinstance(head, nn.Sequential):
        for layer in head:
            if isinstance(layer, nn.Linear):
                return layer.in_features

    raise TypeError(f"Linear head를 찾을 수 없습니다: {type(head)}")



def train_one_epoch_centerloss_dualview(
    model,
    train_loader,
    criterion,
    center_loss_fn,
    optimizer,
    center_optimizer,
    device,
    center_loss_weight=0.02
):
    model.train()
    center_loss_fn.train()

    running_loss = 0.0
    running_ce_loss = 0.0
    running_center_loss = 0.0

    correct = 0
    total = 0

    start_time = time.time()

    progress_bar = tqdm(
        train_loader,
        desc=f"Training CenterLoss Phase weight={center_loss_weight}",
        leave=True
    )

    for batch_idx, (images_global, images_local, labels) in enumerate(progress_bar):
        batch_start = time.time()

        # Phase 2에서는 global view만 사용
        images = images_global.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        center_optimizer.zero_grad(set_to_none=True)

        with autocast():
            logits, features = convnext_forward_with_features(
                model,
                images
            )

            ce_loss = criterion(logits, labels)

            c_loss = center_loss_fn(
                features,
                labels
            )

            loss = ce_loss + center_loss_weight * c_loss

        scaler.scale(loss).backward()

        scaler.step(optimizer)
        scaler.step(center_optimizer)
        scaler.update()

        running_loss += loss.item() * labels.size(0)
        running_ce_loss += ce_loss.item() * labels.size(0)
        running_center_loss += c_loss.item() * labels.size(0)

        _, preds = torch.max(logits, 1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

        current_loss = running_loss / total
        current_ce = running_ce_loss / total
        current_center = running_center_loss / total
        current_acc = correct / total
        batch_time = time.time() - batch_start

        progress_bar.set_postfix({
            "loss": f"{current_loss:.4f}",
            "ce": f"{current_ce:.4f}",
            "center": f"{current_center:.4f}",
            "acc": f"{current_acc:.4f}",
            "sec/batch": f"{batch_time:.2f}"
        })

    epoch_time = time.time() - start_time

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    epoch_ce_loss = running_ce_loss / total
    epoch_center_loss = running_center_loss / total

    return (
        epoch_loss,
        epoch_acc,
        epoch_ce_loss,
        epoch_center_loss,
        epoch_time
    )

num_classes = metadata_df["label"].nunique()
print("num_classes:", num_classes)

model = models.convnext_tiny(weights=models.ConvNeXt_Tiny_Weights.DEFAULT)
#model = models.swin_t(weights=models.Swin_T_Weights.DEFAULT)

in_features = model.classifier[2].in_features
model.classifier[2] = nn.Linear(in_features, num_classes) #마지막 Linear layer
# 기본 구조는 1000개 클래스르르 맞히도록 만들어져서 마지막 분류층에 들어가는 특징 개수를 가져오라는 의미
#그리고 뽑은 이미지 특징 768개를 OfficeHome 클래스 만큼의 점수로 바꿔라

#in_features = model.head.in_features
#model.head = nn.Linear(in_features, num_classes)


# model.fc =nn.Sequential(
#     nn.Dropout(p=0.3),
#     nn.Linear(model.fc.in_features, num_classes),
# ) 여기는 ResNet 할때만

model = model.to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.05)
optimizer = optim.AdamW(model.parameters(),
                        lr=1e-4,
                        weight_decay=2e-4)

class_to_idx = (
    metadata_df[["class_name", "label"]]
    .drop_duplicates()
    .sort_values("label")
    .set_index("class_name")["label"]
    .to_dict()
)

idx_to_class = {
    label: class_name
    for class_name, label in class_to_idx.items()
}

classes = [
    idx_to_class[i]
    for i in range(len(idx_to_class))
]

print("클래스 수:", len(classes))
print("클래스 예시:", classes[:10])

#6.17추가부분
# 점수 낮은 애들을 위한 필터 만들어서 적용

def get_hard_classes_from_val(
    val_labels,
    val_preds,
    classes,
    acc_threshold=0.82,
    max_classes=10,
    priority_names=None
):
    class_acc_df = make_class_accuracy_table(
        labels=val_labels,
        preds=val_preds,
        classes=classes
    )

    hard_df = class_acc_df[
        class_acc_df["accuracy"] < acc_threshold
    ].copy()

    hard_df = hard_df.sort_values("accuracy", ascending=True)

    hard_class_names = hard_df["class_name"].head(max_classes).tolist()

    # 전자기기 계열은 우선 포함
    if priority_names is not None:
        for name in priority_names:
            if name in classes and name not in hard_class_names:
                hard_class_names.append(name)

    return hard_class_names, class_acc_df


from torch.utils.data import WeightedRandomSampler

def make_hard_class_sampler(
    dataset,
    hard_class_names,
    class_to_idx,
    hard_sample_weight=4.0,
    normal_sample_weight=1.0
):
    hard_label_ids = set([
        class_to_idx[name]
        for name in hard_class_names
        if name in class_to_idx
    ])

    sample_weights = []

    for _, row in dataset.df.iterrows():
        label = int(row["label"])

        if label in hard_label_ids:
            sample_weights.append(hard_sample_weight)
        else:
            sample_weights.append(normal_sample_weight)

    sampler = WeightedRandomSampler(
        weights=sample_weights,
        num_samples=len(sample_weights),
        replacement=True
    )

    return sampler


def make_hard_class_weight_tensor(
    num_classes,
    classes,
    hard_class_names,
    device,
    hard_loss_weight=1.4,
    normal_loss_weight=1.0
):
    weights = torch.ones(num_classes) * normal_loss_weight

    for name in hard_class_names:
        if name in classes:
            idx = classes.index(name)
            weights[idx] = hard_loss_weight

    weights = weights.to(device)

    return weights



def train_one_epoch_mixup_dualview_only(
    model,
    train_loader,
    criterion,
    optimizer,
    device,
    alpha=0.15
):
    model.train()

    running_loss = 0.0
    correct_ref = 0
    total = 0

    start_time = time.time()

    progress_bar = tqdm(
        train_loader,
        desc=f"Training Hard Phase MixUp alpha={alpha}",
        leave=True
    )

    for batch_idx, (images_global, images_local, labels) in enumerate(progress_bar):
        batch_start = time.time()

        images = images_global.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        mixed_images, labels_a, labels_b, lam = mixup_data(
            images,
            labels,
            alpha=alpha
        )

        optimizer.zero_grad(set_to_none=True)

        with autocast():
            outputs = model(mixed_images)

            loss = mixup_criterion(
                criterion,
                outputs,
                labels_a,
                labels_b,
                lam
            )

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item() * labels.size(0)

        _, preds = torch.max(outputs, 1)
        correct_ref += (preds == labels_a).sum().item()
        total += labels.size(0)

        current_loss = running_loss / total
        current_acc_ref = correct_ref / total
        batch_time = time.time() - batch_start

        progress_bar.set_postfix({
            "loss": f"{current_loss:.4f}",
            "acc_ref": f"{current_acc_ref:.4f}",
            "sec/batch": f"{batch_time:.2f}"
        })

    epoch_time = time.time() - start_time

    return running_loss / total, correct_ref / total, epoch_time

from torch.cuda.amp import autocast, GradScaler

scaler = GradScaler()

def train_one_epoch_mixup(model, train_loader, criterion, optimizer, device, alpha=0.2):
    model.train()

    running_loss = 0.0
    correct = 0
    total = 0
    top3_sum = 0.0
    batch_count = 0

    start_time = time.time()

    progress_bar = tqdm(train_loader, desc="Training MixUp", leave=True)

    for batch_idx, (images, labels) in enumerate(progress_bar):
        batch_start = time.time()

        images = images.to(device)
        labels = labels.to(device)

        images, labels_a, labels_b, lam = mixup_data(
            images,
            labels,
            alpha = alpha
        )

        optimizer.zero_grad()


        with autocast():
          outputs = model(images)
          loss = mixup_criterion(
              criterion,
              outputs,
              labels_a,
              labels_b,
              lam
              )

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()


        running_loss += loss.item() * images.size(0)

        _, preds = torch.max(outputs, 1)
        correct += (preds == labels_a).sum().item()
        total += labels.size(0)

        current_loss = running_loss / total
        current_acc = correct / total
        batch_time = time.time() - batch_start

        progress_bar.set_postfix({
            "batch": batch_idx + 1,
            "loss": f"{current_loss:.4f}",
            "acc": f"{current_acc:.4f}",
            "sec/batch": f"{batch_time:.2f}"
        })

    epoch_time = time.time() - start_time

    epoch_loss = running_loss / total
    epoch_acc = correct / total

    return epoch_loss, epoch_acc, epoch_time

def topk_accuracy(outputs, labels, k=3):
    with torch.no_grad():
        _, topk_preds = outputs.topk(k, dim=1)
        correct = topk_preds.eq(labels.view(-1, 1).expand_as(topk_preds))
        return correct.any(dim=1).float().mean().item()

def evaluate(model, val_loader, criterion, device):
    model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    top3_sum = 0.0
    batch_count = 0

    all_preds = []
    all_labels = []

    start_time = time.time()

    progress_bar = tqdm(val_loader, desc="Validation", leave=True)

    with torch.no_grad():
        for batch_idx, (images, labels) in enumerate(progress_bar):
            batch_start = time.time()

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)

            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

            top3 = topk_accuracy(outputs, labels, k=3)
            top3_sum += top3
            batch_count += 1

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

            current_loss = running_loss / total
            current_acc = correct / total
            current_top3 = top3_sum / batch_count
            batch_time = time.time() - batch_start

            progress_bar.set_postfix({
                "batch": batch_idx + 1,
                "loss": f"{current_loss:.4f}",
                "acc": f"{current_acc:.4f}",
                "top3" : f"{current_top3:.4f}",
                "sec/batch": f"{batch_time:.2f}"
            })

    epoch_time = time.time() - start_time

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    epoch_top3 = top3_sum / batch_count

    return epoch_loss, epoch_acc, epoch_top3, all_preds, all_labels, epoch_time

def make_class_accuracy_table(labels, preds, classes) :
  labels = np.array(labels)
  preds = np.array(preds)

  rows = []

  for idx, class_name in enumerate(classes):
    mask = labels == idx
    total = mask.sum()

    if total == 0:
      correct = 0
      acc = 0.0

    else :
      correct = int((preds[mask] == labels[mask]).sum())
      acc = correct/ total

    rows.append({
        "class_idx" : idx,
        "class_name" : class_name,
        "total" : int(total),
        "correct" : int(correct),
        "accuracy" : acc
    })
  return pd.DataFrame(rows).sort_values("accuracy", ascending=True)

!pip install -U wandb -q

import wandb
from getpass import getpass

api_key = getpass("W&B API Key 입력 : ")

wandb.login(
    key=api_key,
    relogin=True
)

print("W&B 로그인 완료")


try:
    wandb.finish()
except:
    pass

run = wandb.init(
    project="officehome-product-classification",
    name="convnext-tiny-lightlog-v1",
    group="model_comparison",
    job_type="light_logging",
    config={
        "model": "convnext_tiny",
        "optimizer": "AdamW",
        "lr": 1e-4,
        "weight_decay": 2e-4,
        "batch_size": batch_size,
        "num_classes": num_classes,
        "train_size": len(train_dataset),
        "val_size": len(val_dataset),
    }
)

print("W&B 연결 완료:", run.url)

import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

epochs = 15
patience = 3
min_delta = 0.0005

best_val_acc = 0.0
best_epoch = 0
epochs_no_improve = 0

phase15_changed = False
phase2_changed = False

phase15_trigger_clean_train_acc = 0.86
phase2_trigger_clean_train_acc = 0.94

mixup_alpha = 0.2

center_loss_fn = None
center_optimizer = None
center_loss_weight = 0.0

save_path = "/content/drive/MyDrive/models/officehome_convnext_phase_center_best.pt"
os.makedirs(os.path.dirname(save_path), exist_ok=True)

history = {
    "epoch": [],
    "phase": [],
    "mixup_alpha": [],

    "train_loss_mixup": [],
    "train_acc_ref": [],
    "train_time": [],

    "clean_train_loss": [],
    "clean_train_acc": [],
    "clean_train_time": [],

    "val_loss": [],
    "val_acc": [],
    "val_top3": [],
    "val_time": [],

    "overfit_gap_clean": [],
    "lr": [],
}

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="max",
    factor=0.5,
    patience=1
)

for epoch in range(epochs):
    print(f"\n===== Epoch [{epoch + 1}/{epochs}] =====")

    if phase2_changed:
        current_phase = 2
    elif phase15_changed:
        current_phase = 1.5
    else:
        current_phase = 1

    print("현재 Phase:", current_phase)
    print("현재 MixUp alpha:", mixup_alpha)

    # =========================================================
    # 1. Train
    # =========================================================
    if phase2_changed:
        train_loss, train_acc_ref, ce_loss, center_loss_value, train_time = train_one_epoch_centerloss_dualview(
            model=model,
            train_loader=train_loader,
            criterion=criterion,
            center_loss_fn=center_loss_fn,
            optimizer=optimizer,
            center_optimizer=center_optimizer,
            device=device,
            center_loss_weight=center_loss_weight
        )

        mix_loss = ce_loss
        cons_loss = center_loss_value

    else:
        train_loss, train_acc_ref, mix_loss, cons_loss, train_time = train_one_epoch_mixup_global_consistency(
            model=model,
            train_loader=train_loader,
            criterion=criterion,
            optimizer=optimizer,
            device=device,
            alpha=mixup_alpha,
            consistency_weight=0.1,
            temperature=1.0
        )

    # =========================================================
    # 2. Validation
    # =========================================================
    val_loss, val_acc, val_top3, val_preds, val_labels, val_time = evaluate(
        model=model,
        val_loader=val_loader,
        criterion=criterion,
        device=device
    )

    # =========================================================
    # 3. Clean train acc
    # =========================================================
    clean_train_loss, clean_train_acc, clean_train_time = evaluate_clean_train_acc(
        model=model,
        train_loader=clean_train_loader,
        criterion=criterion,
        device=device,
        max_batches=150
    )

    current_lr = optimizer.param_groups[0]["lr"]
    overfit_gap_clean = clean_train_acc - val_acc

    print(
        f"\nEpoch [{epoch + 1}/{epochs}] 결과\n"
        f"Phase: {current_phase} | MixUp alpha: {mixup_alpha}\n"
        f"Train Total Loss: {train_loss:.4f} | Aux1 Loss: {mix_loss:.4f} | Aux2 Loss: {cons_loss:.4f} | Acc Ref: {train_acc_ref:.4f}\n"
        f"Clean Train Loss: {clean_train_loss:.4f} | Clean Train Acc: {clean_train_acc:.4f}\n"
        f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f} | Val Top3: {val_top3:.4f}\n"
        f"Clean Overfit Gap: {overfit_gap_clean:.4f} | LR: {current_lr}"
    )

    # =========================================================
    # 4. History
    # =========================================================
    history["epoch"].append(epoch + 1)
    history["phase"].append(current_phase)
    history["mixup_alpha"].append(mixup_alpha)

    history["train_loss_mixup"].append(train_loss)
    history["train_acc_ref"].append(train_acc_ref)
    history["train_time"].append(train_time)

    history["clean_train_loss"].append(clean_train_loss)
    history["clean_train_acc"].append(clean_train_acc)
    history["clean_train_time"].append(clean_train_time)

    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)
    history["val_top3"].append(val_top3)
    history["val_time"].append(val_time)

    history["overfit_gap_clean"].append(overfit_gap_clean)
    history["lr"].append(current_lr)

    # =========================================================
    # 5. W&B log
    # =========================================================
    try:
        import wandb

        if wandb.run is not None:
            wandb.log({
                "epoch": epoch + 1,
                "phase": current_phase,

                "mixup/alpha": mixup_alpha,

                "train/total_loss": train_loss,
                "train/acc_ref": train_acc_ref,
                "train/time_sec": train_time,

                "train/aux_loss_1": mix_loss,
                "train/aux_loss_2": cons_loss,
                "train/center_loss_weight": center_loss_weight,

                "clean_train/loss": clean_train_loss,
                "clean_train/acc": clean_train_acc,
                "clean_train/time_sec": clean_train_time,

                "val/loss": val_loss,
                "val/acc_top1": val_acc,
                "val/acc_top3": val_top3,
                "val/time_sec": val_time,

                "diagnostics/overfit_gap_clean": overfit_gap_clean,
                "optimizer/lr": current_lr,
            })
    except Exception as e:
        print("W&B log 실패:", e)

    # =========================================================
    # 6. Best model save
    # =========================================================
    if val_acc > best_val_acc + min_delta:
        best_val_acc = val_acc
        best_epoch = epoch + 1
        epochs_no_improve = 0

        save_dict = {
            "model_state_dict": model.state_dict(),
            "classes": classes,
            "class_to_idx": class_to_idx,
            "val_acc": best_val_acc,
            "val_loss": val_loss,
            "val_top3": val_top3,
            "clean_train_acc": clean_train_acc,
            "epoch": best_epoch,
            "num_classes": num_classes,
            "model_name": "convnext_tiny",
            "phase": current_phase,
            "mixup_alpha": mixup_alpha,
            "phase15_changed": phase15_changed,
            "phase2_changed": phase2_changed,
            "center_loss_weight": center_loss_weight,
            "center_loss_used": phase2_changed,
            "input_size": "224x384",
            "note": "ConvNeXt + Phase + Hard Phase 2 + Center Loss."
        }

        if center_loss_fn is not None:
            save_dict["center_loss_state_dict"] = center_loss_fn.state_dict()

        torch.save(save_dict, save_path)

        print(f"Best model 저장 완료 | Epoch: {best_epoch} | Val Acc: {best_val_acc:.4f}")

    else:
        epochs_no_improve += 1
        print(f"성능 개선 없음: {epochs_no_improve}/{patience}")

    scheduler.step(val_acc)

    # =========================================================
    # 7. Phase 1.5
    # =========================================================
    if (clean_train_acc >= phase15_trigger_clean_train_acc) and (not phase15_changed):
        print("\n" + "=" * 60)
        print(f"Phase 1.5 전환 조건 충족: clean_train_acc={clean_train_acc:.4f} >= {phase15_trigger_clean_train_acc}")
        print("외우기 전 조기개입을 시작합니다.")
        print("하단부는 가리지 않습니다. TV/Monitor/Computer 구조 정보는 보존합니다.")
        print("=" * 60)

        train_dataset.transform_global = phase15_train_transform
        train_dataset.transform_local = consistency_local_transform
        print("train_dataset global/local transform 변경 완료")

        model = add_dropout_to_convnext_classifier(
            model,
            dropout_p=0.1
        )
        model = model.to(device)

        criterion = nn.CrossEntropyLoss(label_smoothing=0.08)
        print("criterion 변경: label_smoothing=0.08")

        for param in model.parameters():
            param.requires_grad = True

        optimizer = optim.AdamW(
            model.parameters(),
            lr=7e-5,
            weight_decay=1e-4
        )
        print("optimizer 변경: 전체 모델 학습 유지, lr=7e-5, weight_decay=1e-4")

        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode="max",
            factor=0.5,
            patience=1
        )
        print("scheduler 재설정 완료")

        mixup_alpha = 0.3
        print("MixUp alpha 변경: 0.3")

        phase15_changed = True
        epochs_no_improve = 0
        print("Phase 1.5 전환 완료, epochs_no_improve 초기화")

    # =========================================================
    # 8. Hard Phase 2 + Center Loss
    # =========================================================
    if (clean_train_acc >= phase2_trigger_clean_train_acc) and phase15_changed and (not phase2_changed):
        print("\n" + "=" * 60)
        print(f"Hard Phase 2 전환 조건 충족: clean_train_acc={clean_train_acc:.4f} >= {phase2_trigger_clean_train_acc}")
        print("저적중률 클래스를 더 자주 보고 Center Loss로 feature를 모읍니다.")
        print("=" * 60)

        priority_names = [
            "Computer",
            "Monitor",
            "TV",
            "Laptop",
            "Printer",
            "Keyboard"
        ]

        hard_class_names, current_class_acc_df = get_hard_classes_from_val(
            val_labels=val_labels,
            val_preds=val_preds,
            classes=classes,
            acc_threshold=0.82,
            max_classes=8,
            priority_names=priority_names
        )

        print("Hard classes:")
        print(hard_class_names)

        display(
            current_class_acc_df[
                current_class_acc_df["class_name"].isin(hard_class_names)
            ].sort_values("accuracy")
        )

        train_dataset.transform_global = phase15_train_transform
        train_dataset.transform_local = consistency_local_transform
        print("train_dataset transform 변경 완료")

        hard_sampler = make_hard_class_sampler(
            dataset=train_dataset,
            hard_class_names=hard_class_names,
            class_to_idx=class_to_idx,
            hard_sample_weight=4.0,
            normal_sample_weight=1.0
        )

        train_loader = DataLoader(
            train_dataset,
            batch_size=batch_size,
            sampler=hard_sampler,
            shuffle=False,
            num_workers=0,
            pin_memory=True if torch.cuda.is_available() else False
        )

        print("Hard class weighted train_loader 생성 완료")

        hard_class_weights = make_hard_class_weight_tensor(
            num_classes=num_classes,
            classes=classes,
            hard_class_names=hard_class_names,
            device=device,
            hard_loss_weight=1.4,
            normal_loss_weight=1.0
        )

        criterion = nn.CrossEntropyLoss(
            weight=hard_class_weights,
            label_smoothing=0.05
        )

        print("Hard class weighted criterion 생성 완료")

        model = freeze_convnext_front_keep_last(model)
        model = model.to(device)

        feat_dim = get_convnext_feature_dim(model)

        center_loss_fn = CenterLoss(
            num_classes=num_classes,
            feat_dim=feat_dim,
            device=device
        )

        center_optimizer = optim.SGD(
            center_loss_fn.parameters(),
            lr=0.5
        )

        center_loss_weight = 0.02

        print("Center Loss 준비 완료")
        print("feat_dim:", feat_dim)
        print("center_loss_weight:", center_loss_weight)

        trainable_params = [
            p for p in model.parameters()
            if p.requires_grad
        ]

        optimizer = optim.AdamW(
            trainable_params,
            lr=3e-5,
            weight_decay=1e-4
        )

        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode="max",
            factor=0.5,
            patience=1
        )

        mixup_alpha = 0.0

        phase2_changed = True
        epochs_no_improve = 0

        print("Hard Phase 2 + Center Loss 전환 완료")
        print("MixUp alpha:", mixup_alpha)

    # =========================================================
    # 9. Early stopping
    # =========================================================
    if epochs_no_improve >= patience:
        print(f"Early stopping 발생 | Epoch {epoch + 1}")
        break


# =========================================================
# Final summary
# =========================================================
class_acc_df = make_class_accuracy_table(
    labels=val_labels,
    preds=val_preds,
    classes=classes
)

try:
    import wandb

    if wandb.run is not None:
        wandb.run.summary["best_val_acc"] = best_val_acc
        wandb.run.summary["best_epoch"] = best_epoch
        wandb.run.summary["final_val_acc"] = val_acc
        wandb.run.summary["final_clean_train_acc"] = clean_train_acc

        wandb.log({
            "tables/class_accuracy": wandb.Table(dataframe=class_acc_df)
        })

        wandb.finish()

except Exception as e:
    print("W&B finish 실패:", e)

print("\n학습 완료")
print("Best Val Acc:", round(best_val_acc, 4))
print("Best Epoch:", best_epoch)
print("저장 경로:", save_path)
print("Phase 1.5 전환 여부:", phase15_changed)
print("Phase 2 전환 여부:", phase2_changed)

confusion_df = pd.DataFrame({
    "true_label": [classes[i] for i in val_labels],
    "pred_label": [classes[i] for i in val_preds],
})

wrong_df = confusion_df[
    confusion_df["true_label"] != confusion_df["pred_label"]
]

confusion_pairs = wrong_df.groupby(
    ["true_label", "pred_label"]
).size().reset_index(name="count").sort_values(
    "count",
    ascending=False
)

display(confusion_pairs.head(40))

# 이미 학습이 끝난 상태에서
# Grad-CAM / confidence / entropy / margin / CAM 수치 그래프를 W&B에 올리는 코드


#여기부터는 만들었다기 보다는 내 의견을 가지고 GPT가 해석한 경향성이 큰 코드들임zxcv

import wandb

run = wandb.init(
    project="officehome-product-classification",
    name="convnext-posthoc-attention-graph",
    group="attention_analysis",
    job_type="posthoc_gradcam_diagnostics",
    config={
        "model": "convnext_tiny",
        "analysis": "posthoc_attention_diagnostics"
    }
)

# attention_df가 이미 만들어져 있다고 가정
# 없으면 먼저 analyze_model_attention(...)으로 생성 필요

wandb.log({
    "attention/diagnostics_table": wandb.Table(dataframe=attention_df),

    "attention/confidence_vs_true_prob": wandb.plot.line_series(
        xs=attention_df["sample_idx"].tolist(),
        ys=[
            attention_df["confidence"].tolist(),
            attention_df["true_prob"].tolist()
        ],
        keys=["Prediction confidence", "True class probability"],
        title="Prediction confidence vs true class probability",
        xname="Sample index"
    ),

    "attention/entropy": wandb.plot.bar(
        wandb.Table(
            dataframe=attention_df[["sample_idx", "entropy"]]
        ),
        "sample_idx",
        "entropy",
        title="Prediction uncertainty entropy"
    ),

    "attention/top1_top2_margin": wandb.plot.bar(
        wandb.Table(
            dataframe=attention_df[["sample_idx", "margin_top1_top2"]]
        ),
        "sample_idx",
        "margin_top1_top2",
        title="Decision margin: Top1 - Top2 probability"
    ),

    "attention/cam_energy_concentration": wandb.plot.line_series(
        xs=attention_df["sample_idx"].tolist(),
        ys=[
            attention_df["cam_center_energy"].tolist(),
            attention_df["cam_top10_energy"].tolist()
        ],
        keys=["Center energy", "Top 10% energy"],
        title="Grad-CAM attention concentration",
        xname="Sample index"
    )
})

wandb.finish()

